name = "SEEK Fundamental Quant Rank"
shortcode = "seek"
description = "A strategy that invests directly in stocks based on quantitative ratings of the stocks fundamentals relative to its peer group"
source = "https://seekingalpha.com"
version = "1.1.0"
benchmark = { compositeFigi = "BBG000BHTMY2", ticker = "VFINX", name = "Vanguard 500 Index Fund Investor Shares" }

[arguments.numHoldings]
name = "Number of Holdings"
description = "Maximum number of stocks to hold at a time"
typecode = "number"
default = "50"

[arguments.indicator]
name = "Risk-On Indicator"
description = "Indicator to decide when to invest in risky assets vs safe haven assets"
typecode = "choice"
default = "None"
options = ["None", "Momentum"]

[arguments.outTicker]
name = "Out-of-Market Ticker"
description = "Ticker to use when sentiment model score is below 0"
typecode = "stock"
default = '{"compositeFigi": "BBG000BCKYB1", "ticker": "VUSTX", "name": "Vanguard Long Term Treasury Fund"}'

[arguments.period]
name = "Rebalance Frequency"
description = "Frequency portfolio holdings should be rebalanced"
typecode = "choice"
default = "Weekly"
options = ["Weekly", "Monthly"]

[arguments.minMarketCap]
name = "Minimum Market Capitalization (mil)"
description = "Minimum market capitalization in millions"
typecode = "number"
advanced = true
default = "0"

[suggested.SEEK-Default]
numHoldings = "50"
indicator = "None"
outTicker = "VUSTX"
period = "Weekly"
