name = "Seeking Alpha Quant Rank"
shortcode = "seek"
description = "A strategy that invests directly in stocks based on quantitative ratings from Seeking Alpha"
source = "https://seekingalpha.com"
version = "1.0.0"
benchmark = "VFINX"

[arguments.outTicker]
name = "Out-of-Market Ticker"
description = "Ticker to use when sentiment model score is below 0"
typecode = "string"
default = "VUSTX"

[arguments.numHoldings]
name = "Number of Holdings"
description = "Maximum number of stocks to hold at a time"
typecode = "number"
default = "100"

[arguments.period]
name = "Rebalance Frequency"
description = "Frequency portfolio holdings should be rebalanced"
typecode = "choice"
default = "weekly"
options = ["weekly", "monthly"]